/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_reigns_FolderJNI */

#ifndef _Included_com_reigns_FolderJNI
#define _Included_com_reigns_FolderJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_reigns_FolderJNI
 * Method:    showFolderRights
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_reigns_FolderJNI_showFolderRights
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
